apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-subkube
  name: hello-subkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-subkube
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-subkube
    spec:
      containers:
      - image: ealen/echo-server:latest
        name: echoserver
        resources: {}
status: {}
